version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - mongo
  #  Mongodb service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/      # Mount a volume for MongoDB data storage
volumes:
  mongodb_data:                  # Create a volume for MongoDB data storage